"""add created_at to users

Revision ID: 1112e61374a5
Revises: 6642d976a3be
Create Date: 2026-01-20 23:28:21.098959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1112e61374a5'
down_revision = '6642d976a3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.alter_column('gym_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.alter_column('gym_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
