"""add cascade deeltes

Revision ID: 22c65580fd2f
Revises: 
Create Date: 2026-03-13 12:00:53.643500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22c65580fd2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_trainer_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('attendance_client_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['trainer_id'], ['id'])

    with op.batch_alter_table('gym_pricing', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('gym_pricing_gym_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'gyms', ['gym_id'], ['id'])

    with op.batch_alter_table('gym_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('gym_subscriptions_gym_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'gyms', ['gym_id'], ['id'])

    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payments_gym_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'gyms', ['gym_id'], ['id'])

    with op.batch_alter_table('progress_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('progress_logs_client_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('progress_logs_trainer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['trainer_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['client_id'], ['id'])

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('schedules_trainer_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('schedules_gym_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'gyms', ['gym_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['trainer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('subscriptions_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('workout_days', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('workout_days_plan_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'workout_plans', ['plan_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('workout_plans_trainer_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('workout_plans_client_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['trainer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('workout_plans_client_id_fkey'), 'users', ['client_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('workout_plans_trainer_id_fkey'), 'users', ['trainer_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('workout_days', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('workout_days_plan_id_fkey'), 'workout_plans', ['plan_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subscriptions_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('schedules_gym_id_fkey'), 'gyms', ['gym_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('schedules_trainer_id_fkey'), 'users', ['trainer_id'], ['id'])

    with op.batch_alter_table('progress_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('progress_logs_trainer_id_fkey'), 'users', ['trainer_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('progress_logs_client_id_fkey'), 'users', ['client_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payments_gym_id_fkey'), 'gyms', ['gym_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('gym_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('gym_subscriptions_gym_id_fkey'), 'gyms', ['gym_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('gym_pricing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('gym_pricing_gym_id_fkey'), 'gyms', ['gym_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_client_id_fkey'), 'users', ['client_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('attendance_trainer_id_fkey'), 'users', ['trainer_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
