"""empty message

Revision ID: 2663b3c1dfaa
Revises: 9194c79a5242
Create Date: 2026-03-03 11:16:56.483291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2663b3c1dfaa'
down_revision = '9194c79a5242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_chat_lookup', ['sender_id', 'receiver_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_lookup')

    # ### end Alembic commands ###
