"""add full_name to user

Revision ID: 31330c24f4df
Revises: 503cb90e6c95
Create Date: 2026-01-22 22:20:17.050786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31330c24f4df'
down_revision = '503cb90e6c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
