"""expiring announcement added

Revision ID: 9194c79a5242
Revises: a7bba3d5a9b6
Create Date: 2026-03-02 22:16:00.348597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9194c79a5242'
down_revision = 'a7bba3d5a9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
