"""cascade workout hierachy

Revision ID: c40c03837c87
Revises: 22c65580fd2f
Create Date: 2026-03-13 12:05:28.637634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40c03837c87'
down_revision = '22c65580fd2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('workout_exercises_day_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'workout_days', ['day_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('workout_exercises_day_id_fkey'), 'workout_days', ['day_id'], ['id'])

    # ### end Alembic commands ###
