"""add cascade deletes

Revision ID: c4366eb2047b
Revises: 37b1d7445693
Create Date: 2026-03-18 14:50:05.432780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4366eb2047b'
down_revision = '37b1d7445693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_pricing', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('gym_pricing_gym_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'gyms', ['gym_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('gym_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('gym_subscriptions_gym_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'gyms', ['gym_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payments_gym_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'gyms', ['gym_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payments_gym_id_fkey'), 'gyms', ['gym_id'], ['id'])

    with op.batch_alter_table('gym_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('gym_subscriptions_gym_id_fkey'), 'gyms', ['gym_id'], ['id'])

    with op.batch_alter_table('gym_pricing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('gym_pricing_gym_id_fkey'), 'gyms', ['gym_id'], ['id'])

    # ### end Alembic commands ###
