"""add gym status

Revision ID: d5b55d99a4c5
Revises: c40c03837c87
Create Date: 2026-03-13 12:26:21.208810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b55d99a4c5'
down_revision = 'c40c03837c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
